remoteoss/remote-flows

- package-lock.json
- package.json
- src/components/form/fields/SelectField.tsx
- src/components/ui/button.tsx
- src/components/ui/form.tsx
- src/components/ui/label.tsx
- src/components/ui/select.tsx
- src/flows/CostCalculator.tsx
- src/styles/global.css
- src/types.ts
This PR wraps Select with shadcn FormField.
**How to test:**
Import `CostCalculator` in your consumer app, like so:
```jsx
import { CostCalculator } from "@remoteoss/remote-flows/flows/CostCalculator";
<ThemeProvider theme={{ colors: { dangerBackground: "black" } }}>
<CostCalculator /> 
</ThemeProvider>
```
> feat(select-field): Select as a form field

- package-lock.json
- package.json
- src/RemoteFlowsProvider.tsx
- src/flows/CostCalculator.tsx
- src/flows/hooks.ts
- src/index.tsx
Implemented the cost calculator flow using react-query. I implemented the thing with ReactQueryProvider inserted in the RemoteFlows provider.
Haven't tested yet what happens with multiple providers in the page, but according to ChatGPT it should work
## How to test
in the App.tsx
```
import { useState } from "react";
import { RemoteFlows } from "@remoteoss/remote-flows";
import { CostCalculator } from "@remoteoss/remote-flows/flows/CostCalculator";
import "./App.css";
const ACCESS_TOKENS = {
PARTNER: "<PARTNER_TOKEN>",
NEW_COMPANY: "<COMPANY_TOKEN>",
};
function App() {
const [estimations, setEstimations] = useState(null);
return (
<RemoteFlows
auth={() =>
Promise.resolve({
expires_in: 3600,
access_token: ACCESS_TOKENS.PARTNER,
})
}
>
<CostCalculator onSubmit={(response) => …
```
> feat(cost-calculator) - implement endpoints with react-query

- src/flows/CostCalculator/CostCalculator.tsx
We removed the useEffect and forgot to assign the ref after we retrieve data from the region/:slug/fields schema
> fix(json-schema) - bring back validation from json-schema #17

- example/src/App.css
- example/src/App.tsx
- package-lock.json
- package.json
- src/components/ui/button.tsx
- src/components/ui/drawer.tsx
- src/components/ui/scroll-area.tsx
- src/flows/CostCalculator/CostCalculator.tsx
- src/flows/CostCalculator/Disclaimer/Disclaimer.tsx
- src/flows/CostCalculator/Disclaimer/index.ts
- src/flows/CostCalculator/hooks.ts
- src/index.tsx
- src/styles/global.css
Implemented a disclaimer component that is rendered inside the cost calculator, we also offer a hook, that way partners can rely on the data and be more opinionated about the styles.
In the example folder, I added some css on how one can style the drawer.
Add new dependencies from shadcn to load drawers.
In the root folder run, nothing changed here
```
npm run dev
```
after that 
create a .env file inside /example
```
CLIENT_ID=<CLIENT_ID>
CLIENT_SECRET=<CLIENT_ID>
REMOTE_GATEWAY=<STAGING_GATEWAY>
```
```
cd example
npm run dev
```
Open localhost:3001 and the app should work
> feat(disclaimer) - add disclaimer to the cost calculator

- example/src/App.tsx
- src/flows/CostCalculator/CostCalculator.tsx
- src/flows/CostCalculator/hooks.ts
- src/flows/CostCalculator/tests/CostCalculator.test.tsx
- src/flows/CostCalculator/tests/fixtures.ts
I noticed when you set a country with defaultValues that had region fields like Japan, the JSON schema wasn't getting fetched.
I fixed it and add some tests as I discovered this problem when I was doing some.
> fix(cost-calculator) - load region fields if a country has them

- example/src/App.tsx
- src/flows/CostCalculator/CostCalculator.tsx
- src/flows/CostCalculator/hooks.ts
- src/flows/CostCalculator/index.ts
- src/flows/CostCalculator/tests/CostCalculator.test.tsx
- src/flows/CostCalculator/types.ts
- src/flows/CostCalculator/utils.ts
- src/flows/types.ts
- src/index.tsx
- src/lib/utils.ts
`onSubmit` function in `useCostCalculator` should validate form fields before posting the estimation to Remote API. 
If partners use `useCostCalculator` directly they might not have a validation in place, so this change ensures that fields validation is always executed before sending the request.
Beside including the validation, this PR also changes the `onSubmit` parameters. The hook should be responsible for formatting the request payload, not the component.
> chore(useCostCalculator): Move form validation to onSubmit

- README.md
- example/src/App.css
- example/src/App.tsx
- src/flows/CostCalculator/CostCalculator.tsx
- src/flows/CostCalculator/hooks.ts
- src/flows/CostCalculator/tests/CostCalculator.test.tsx
- src/flows/types.ts
This PR adds `isLoading` and `isSubmitting` to `useCostCalculator` hook.
- `isLoading` state derives from loading countries, currencies and region field
- `isSubmitting` state derives from the mutation isPending state
It also adds `useCostCalculator` documentation and some minor CSS improvements to the cost calculator example
> feat(CostCalculator): support isLoading and isSubmitting

- src/components/form/fields/SelectField.tsx
- src/components/form/fields/TextAreaField.tsx
- src/components/form/fields/TextField.tsx
- src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
Set the labels also as placeholders.
From what I gather the next inputs can have placeholders
* input
* textarea
* select
The datepicker cannot have a placeholder as we render a button, I am guessing partners we'll need to use labels for that.
> feat(forms) - Set labels as placeholders

- example/src/App.tsx
- example/src/BasicCostCalculator.tsx
- src/flows/CostCalculator/CostCalculatorResetButton.tsx
- src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
We had a report that we were passing the onClick handler to the `CostCalculatorResetButton ` the form fields weren't resetting any longer.
This was happening as we were overriding the onClick prop, now this doesn't happen anymore and it's catch by the tests
> fix(cost-calculator) - fix reset handler

- src/components/form/utils.ts
- src/flows/Termination/hooks.ts
- src/flows/Termination/jsonSchema.ts
- src/flows/utils.ts
As the BE now accepts new fields like
* customer_informed_employee
* agrees_to_pto_amount
* agrees_to_pto_amount_notes
* acknowledge_termination_procedure
We can clean a little bit, we need to parse manually the radio values from yes/no to booleans to make it work
> feat(termination) - clean submit form

- example/src/App.css
- example/src/ContractAmendment.tsx
- src/flows/ContractAmendment/ContractAmendmentForm.tsx
Improve Contract Amendment example by showing an error when the form is submitted without any contract details changed.
Test:
- Change `Effective date of change`
- Submit form
An error should be rendered at the bottom of the form:
> chore(contract amendment): Add error handling for contract amendment 

- src/flows/Termination/hooks.ts
Found this bug when testing some stuff related to the termination, we broke it earlier as we were depending in booleans before
> fix(termination) - fix employee awarness bug

- src/components/form/fields/CheckBoxField.tsx
- src/components/form/fields/tests/CheckBoxField.test.tsx
- src/flows/Termination/hooks.ts
- src/flows/Termination/jsonSchema.ts
Did some changes to support multiple checkboxes when using json schemas.
I did the changes using the Checkbox as it will allow us to select multiple options and we do not longer need to parse the values onSubmit as the values will be stored in an array
https://github.com/user-attachments/assets/f4af23cb-dd36-47c3-b89f-d618bbc704b1
Things that I didn't do in this PR:
* Test default values of the checkboxes
> feat(checkboxes) - render multiple checkboxes

- example/server.js
- example/src/ContractAmendment.tsx
- src/RemoteFlowsProvider.tsx
- src/tests/useAuth.test.tsx
- src/types/remoteFlows.ts
- src/useAuth.ts
Currently, the SDK makes direct API calls to Remote API from the frontend. This is problematic for endpoints that require client tokens, as these tokens would be exposed in the frontend code.
This PR allows setting a proxy server in the SDK to avoid this problem.
> feat(proxy): Add proxy support to useAuth and related components

- example/src/Termination.tsx
- src/components/ui/form.tsx
Inject component into description, if we inline functions we need a way to render the component, I think most of the times inline function is what we want to add different props
> feat(termination) - inject components into description

- src/components/form/utils.ts
JSON Schemas can have "ack" checkboxes, where a const value is provided, which means the checkbox values needs to use to value, when the form is submit. 
```json
{
"part_time_salary_confirmation": {
"const": "acknowledged",
"description": "We'll include salary changes in the employment agreement amendment, so please double-check that it's correct.",
"title": "I confirm that this amount is the full annual salary for this part-time employee.",
"type": "string",
"x-jsf-presentation": {
"inputType": "checkbox"
}
}
}
```
Currently this isn't happening in the SDK and the value sent is `true` instead of `acknowledged`, like in the example.
> fix(checkbox): handle const values in checkboxes

- src/components/form/fields/FileUploadField.tsx
- src/components/ui/file-uploader.tsx
There was a button that was submitting the form as the type was not specified
> fix(file-uploads) - avoid submission when opening the file selector

- src/components/form/Statement.tsx
Make statement title optional to fix handling of undefined titles.
> fix(statement): make title prop optional in Statement component

- src/flows/ContractAmendment/ContractAmendmentConfirmationForm.tsx
- src/flows/ContractAmendment/ContractAmendmentForm.tsx
- src/flows/ContractAmendment/hooks.ts
- src/flows/ContractAmendment/tests/ContractAmendmentFlow.test.tsx
Fixes a bug in the contract amendment payload that was sending an empty object. This issue was introduced when we switched to using useStepState.
> fix(contract amendment): update default form values to use stepState

- src/components/form/JSONSchemaForm.tsx
- src/components/form/fields/CheckBoxField.tsx
- src/components/form/fields/CountryField.tsx
- src/components/form/fields/DatePickerField.tsx
- src/components/form/fields/EmailField.tsx
- src/components/form/fields/FileUploadField.tsx
- src/components/form/fields/NumberField.tsx
- src/components/form/fields/RadioGroupField.tsx
- src/components/form/fields/SelectField.tsx
- src/components/form/fields/TextAreaField.tsx
- src/components/form/fields/TextField.tsx
- src/components/form/fields/tests/CheckBoxField.test.tsx
- src/components/form/fields/tests/CountryField.test.tsx
- src/components/form/fields/tests/DatePickerField.test.tsx
- src/components/form/fields/tests/FileUploadField.test.tsx
- src/components/form/fields/tests/NumberField.test.tsx
- src/components/form/fields/tests/RadioGroupField.test.tsx
- src/components/form/fields/tests/SelectField.test.tsx
- src/components/form/fields/tests/TextAreaField.test.tsx
- src/components/form/fields/tests/TextField.test.tsx
- src/flows/Onboarding/BenefitsForm.tsx
- Updated various field components to accept a `component` prop for custom rendering.
- Modified JSONSchemaFormFields to use the new `components` prop for dynamic field rendering.
- Introduced BenefitsForm component to manage form submission and integrate JSONSchemaFormFields with custom components.
> feat(form): enhance fields with component prop support

- src/flows/Onboarding/ContractDetailsStep.tsx
- src/flows/Onboarding/hooks.ts
- Updated `ContractDetailsStep` to use `onboardingBag.initialValues.contract_details` for default values in `OnboardingForm`.  
- Enhanced submission logic to handle both creation and update of employment based on the presence of `internalEmploymentId`.
> feat(onboarding): integrate initial values for contract details

- src/flows/Onboarding/hooks.ts
- src/flows/utils.ts
We're not passing money values in cents to `createHeadlessForm` to that computed values in `x-jsf-logic`. This PR creates introduces:
- a function to get all the money fields and convert the correspondent value to cents before passing it to `createHeadlessForm`
- a small refactor to `useJSONSchemaForm` form
> fix(onboarding): fix the values passed to createHeadlessForm

- src/flows/Onboarding/tests/OnboardingFlow.test.tsx
I was seeing some timeouts, I believe dividing the tests in two will help in having less timeouts
> chore(onboarding) - divide tests in two to go faster

- example/src/App.css
- example/src/Onboarding.tsx
- example/src/OnboardingWithCustomBenefits.tsx
- example/src/OnboardingWithoutSelectCountryStep.tsx
- example/src/ReviewStep.tsx
- src/flows/Onboarding/OnboardingBack.tsx
- src/flows/Onboarding/OnboardingInvite.tsx
- src/flows/Onboarding/hooks.ts
- src/flows/Onboarding/tests/OnboardingBack.test.tsx
- src/flows/Onboarding/utils.ts
- src/flows/useStepState.ts
When recover an employment, who is invited, we moved the user to the review step which means that we cannot longer go back.
Besides API doesn't let do any updates to an employment in that situation
> feat(onboarding) - prevent user from going back when they're in a final status

- src/client/sdk.gen.ts
- src/client/types.gen.ts
Update the open api types to the last version
This will allow us to use the convertCurrency new endpoint, I detected that some of the endpoints like amendments now support json_schema_version.
I've created issues internally to add support for it later
> update open api types to last version

- README.md
I forgot to add a link to the new Readme
> fix(readme) - add onboarding link

- src/flows/Onboarding/tests/OnboardingFlow.test.tsx
Yesterday I had to skip some unit tests to release a new version.
In local using fireEvent reduces the test by 500ms
> fix(onboarding) - remove userEvent, use fireEvent.change

- README.md
- example/server.js
- example/src/RemoteFlows.tsx
- src/RemoteFlowsProvider.tsx
- src/environments.ts
- src/tests/useAuth.test.tsx
- src/types/remoteFlows.ts
- src/useAuth.ts
Replace the deprecated `isTestingMode` boolean prop with the new `environment` prop, providing users with more granular control over Remote API base url.
**More explicit**: Users can now specify exactly which environment they want to connect to instead of a vague "testing mode"
**Better developer experience**: Clear environment options 
**Flexibility**: Supports all available Remote environments (partners, production, sandbox, staging) rather than just production/sandbox toggle
With this change `VITE_REMOTE_GATEWAY` env variable by the `example` project needs to be one of the values: production, staging, partners or sandbox.
> feat(RemoteFlows): Add support to environment prop

- example/src/OnboardingWithoutSelectCountryStep.tsx
- src/flows/Onboarding/OnboardingFlow.tsx
- src/flows/Onboarding/SaveDraftButton.tsx
- src/flows/Onboarding/hooks.tsx
- src/flows/Onboarding/tests/OnboardingFlow.test.tsx
- src/flows/Onboarding/tests/SaveDraftButton.test.tsx
- src/flows/Onboarding/tests/helpers.ts
Add a draft button, which saves the data into the form but it doesn't advance to the next step
Partners want to have a button that saves and then they can listen to the onSuccess callback and navigate to other page
> feat(onboarding) - add save draft button functionality

- example/src/CostCalculatorWithPremiumBenefits.tsx
- src/flows/CostCalculator/Results/CostCalculatorResults.tsx
- src/flows/CostCalculator/tests/utils.test.ts
- src/flows/CostCalculator/utils.ts
Removes the hardcoded EURO sign
stops overriding the conversion rate, and adds isClientToken to the endpoint.
I will need a release to point to once it's merged, so i can update package.json.
I think we should setup vercel to always use the local directory, but i think we need a monorepo setup on vercel for that, not critical, but a bit annoying to have to always update package.json, since you almost always want to point to master. or splitting the apps to make it clearer, not sure, no strong opinion.
> feat: disable overridding currency rate & use client token in premium cc

- package-lock.json
- src/components/form/fields/FieldSetField.tsx
This PR fixes a bug where the error state is not properly updated when a field is inside a fieldset. Even though these fields have no errors, the UI would continue to indicate that an error existed.
The root cause of this behavior with fieldsets isn't entirely clear, so the solution involves triggering manual validation for fieldsets whenever one of their values changes.
> fix(fieldsets): Trigger manual validation

- src/flows/Onboarding/api.ts
Fix the default values for the review step when:
- `I don't want to offer this benefit.` is the selected option
- A benefit is selected under a different tab
> fix(onboarding): Fix selected benefits

- src/components/form/JSONSchemaForm.tsx
- src/components/form/fields/MultiSelectField.tsx
- src/components/form/fields/SelectField.tsx
- src/components/form/fields/fieldsMapping.tsx
- src/components/form/fields/tests/MultiSelectField.test.tsx
- src/components/form/fields/types.ts
- src/components/ui/multi-select.tsx
- src/flows/Onboarding/hooks.tsx
- src/tests/testHelpers.ts
- Fixed: `probation_length_days` (or any `select` with numbers as values) is now submitted as an integer instead of a string
- Fixed: `probation_length_days` is no longer submitted when "Add a probation period" is set to "no". The fix is agnostic, which means that a field that isn't visible won't be part of the payload.
- Fixed: Weekly days off are now properly submitted as an array (e.g., `["tuesday"]` or `["tuesday", "wednesday"]`) instead of a single string
> fix(onboarding): Support to multi select and bug fixing

- src/flows/CostCalculator/CostCalculatorFlow.tsx
- src/flows/CostCalculator/README.md
- src/flows/CostCalculator/hooks.tsx
- src/flows/CostCalculator/tests/utils.test.ts
- src/flows/CostCalculator/utils.ts
Introduced `version` prop with options `standard` and `marketing` and updated `buildPayload` function to conditionally include `annual_gross_salary` based on the version.
> feat(cost-calculator): Add version parameter to CostCalculatorFlow

- src/components/form/utils.ts
- src/flows/Onboarding/hooks.tsx
Some ack fields are not stored in the database, such as "ack_start_date_ammendment" for Argentina, and therefore are not returned in the employment response. Ideally, the solution should be implemented on the backend, with the employment response including these fields. For now, the solution is to enable the ack fields whenever an employmentId exists (for example, when an onboarding is saved as a draft), as this indicates that the user has already started the onboarding process.
> fix(onboarding): enable ack when an employment id exists

- example/src/Components.tsx
- src/components/form/fields/CurrencyConversionField.tsx
- src/components/form/fields/MoneyField.tsx
- src/components/form/fields/NumberField.tsx
- src/components/form/fields/TextField.tsx
- src/components/form/fields/fieldsMapping.tsx
We had a bug report that we very big salaries were a problem.
I decided to put a limit on how big the number is
To do this, I added the maxLength attribute to the AnnualGrossSalary fields and I created a MoneyField which wraps the NumberField
This change affects to the AnnualGrossSalary but also to the salary field in the cost calculator
> feat(money) - avoid big salaries that aren't supported by the API

- src/components/form/fields/FieldSetField.tsx
While testing the onboarding flow for the Dominican Republic, I found that `multi-select` (example in the screenshot) was not rendering properly (it was rendered as a single select) inside fieldsets. This PR resolves this issue.
> fix(FieldSetField): add support for multiple select fields based on inputType

- src/components/form/fields/FieldSetField.tsx
This makes the form to behave better. instead of touching a fieldset and invalidating the whole form, we wait to see if there has been a full submission of the form
> feat(onboarding) - improve validation ux

- tsup.config.ts
After I saw that if you fix in the consumer app the react-hook-form version, I decided to bundle the dependencies and that way, I hope the bug gets solved
We can create a prerelease to check if everything works as expected
> fix(form) - bundle dependencies to avoid duplicated dependencies

- example/src/OnboardingWithoutSelectCountryStep.tsx
- example/src/ReviewStep.tsx
- src/flows/Onboarding/components/ReviewStep.tsx
- src/flows/Onboarding/hooks.tsx
- src/flows/Onboarding/tests/ReviewStep.test.tsx
- src/flows/Onboarding/types.ts
- src/flows/Onboarding/utils.ts
I did several improvements based on feedback for the review step
* Add referred status to the review step to have the different sections better organised
* Add canInvite property that let's the consumer know when the employee can be invited
The second point moves code from the example app to the SDK, with this maybe it's easier for consumers to understand what's happening
> feat(onboarding) - improve onboarding button disabled status

- src/components/form/fields/SelectField.tsx
- src/components/form/fields/tests/SelectField.test.tsx
Updated the SelectField component to streamline the value casting logic. The value is now cast to a number only when `jsonType` is 'number', improving clarity and maintainability.
> refactor(SelectField) - simplify value casting logic based on jsonType

- example/src/CostCalculatorWithResults.tsx
- src/flows/CostCalculator/CostCalculatorForm.tsx
- src/flows/CostCalculator/README.md
- src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
I did a new feature in the CostCalculator to only reset certain fields
In this case, we want to reset only country but not salary or currency
> feat(cost-calculator) - reset form fields explicitly

- src/flows/CostCalculator/Results/CostCalculatorExtraStatutoryPaymentsBreakdown.tsx
- src/flows/CostCalculator/Results/CostCalculatorIndirectTax.tsx
- src/flows/CostCalculator/Results/CostCalculatorResults.tsx
- src/lib/utils.ts
We want to add extra statuory payments and indirect tax sections to the cost calculator results
You can do this by using Bolivia as a country
BTW: tooltips doesn't work but in the entire cost calculator, I am trying to fix in a separated PR
> fix(cost-calculator) - add extra statuory payments and indirect tax

- src/components/form/JSONSchemaForm.tsx
- src/components/form/fields/FieldSetField.tsx
- src/flows/utils.ts
The `JSONSchemaForm` component was using `inputType` when it should have been using `type`. These properties are usually the same, but they differ when `type` is hidden. This caused a bug in the UK onboarding contract details, where the pension scheme was incorrectly displayed.
**Fix**
Update `JSONSchemaForm` component to use `type` instead of `inputType`.
> fix(JSONSchemaForm): Hidden fields support

- example/src/main.tsx
- src/components/form/fields/ForcedValueField.tsx
- src/components/form/fields/tests/ForcedValueField.test.tsx
We had a report for the croatia contract details that we weren't rendering a description.
This was due to that the statement.description was undefined but the description contained the value
It feels similar to this [bug](https://github.com/remoteoss/remote-flows/pull/377)
> fix(forced-value) - fix description which isn't rendered

- src/flows/CostCalculator/hooks.tsx
If you select a employer billing currency which is a different one from the country selected, the currency order will be first the employer billing currency and then the conversion
> feat(cost-calculator) - change currency order

- example/src/CostCalculatorWithPremiumBenefits.tsx
- example/src/Onboarding.tsx
- src/client/sdk.gen.ts
- src/client/types.gen.ts
- src/components/form/fields/CurrencyConversionField.tsx
- src/components/form/fields/tests/CurrencyConversionField.test.tsx
- src/flows/CostCalculator/CostCalculatorFlow.tsx
- src/flows/CostCalculator/components/SalaryField.tsx
- src/flows/CostCalculator/hooks.tsx
- src/flows/CostCalculator/types.ts
- src/flows/Onboarding/api.ts
- src/flows/Onboarding/components/AnnualGrossSalary.tsx
- src/flows/Onboarding/tests/OnboardingFlow.test.tsx
We want that our platform and the SDK will be more similar when doing conversions.
The raw endpoint supports a similar conversion and it's supposed to work for the Onboarding and Marketing Cost Calculator
The effective endpoint is a replacement of the previous endpoint used
> feat(cost-calculator) - call new conversion endpoints

- src/components/form/fields/CurrencyConversionField.tsx
- src/flows/CostCalculator/CostCalculatorFlow.tsx
- src/flows/CostCalculator/CostCalculatorForm.tsx
- src/flows/CostCalculator/hooks.tsx
- src/flows/CostCalculator/jsonSchema.ts
- src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
- src/flows/CostCalculator/tests/utils.test.ts
- src/flows/CostCalculator/types.ts
- src/flows/CostCalculator/utils.ts
When the user types the salary into the employer currency, we should use that one instead of the converted amount when estimating on the backend, so that the results are consistent.
To do that:
- We keep track of whether the user has typed into the conversion input
- We surface that information to the submit value, and we set either annual_gross_salary or annual_gross_salary_in_employer_currency based on whether the user has inputted in one or the other currency.
> feat: use annual_gross_salary_in_employer_currency

- src/flows/CostCalculator/CostCalculatorFlow.tsx
- src/flows/CostCalculator/hooks.tsx
- src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
- src/flows/CostCalculator/tests/fixtures.ts
- src/flows/CostCalculator/tests/hooks.test.tsx
When we pass defaultValues I discover that the internal state was not getting set correctly, detected this while I was coding 
https://github.com/remoteoss/remote-flows/pull/406
Once I fix the behavior tests started to fail, because we weren't considering that POL had regions mocked
I fix the tests and add some
> fix(cost-calculator)- Correct initialization state

- example/src/CostCalculatorWithPremiumBenefits.tsx
- example/src/css/main.css
- src/components/form/fields/FieldSetField.tsx
- src/components/form/fields/tests/FieldSetField.test.tsx
I did an improvement on the fieldsets to allow them to have variants.
This allow us to improve the styling without affecting partners style, if they wanted fieldsets with the inset variant, they could migrate to it
> feat(cost-calculator) - Improve fieldsets for demo

- src/flows/CostCalculator/tests/utils.test.ts
- src/flows/CostCalculator/utils.ts
As I haven't released into a new version, we can still modify the discount that we send
The management fee was appearing in the pdf and we don't want that for now
> fix(cost-calculator) - fix discount title by not adding anything

- example/src/Components.tsx
- example/src/ZendeskDialog.tsx
- package-lock.json
- package.json
- src/components/shared/zendesk-drawer/ZendeskDrawer.tsx
- src/components/shared/zendesk-drawer/api.ts
- src/components/shared/zendesk-drawer/tests/ZendeskDrawer.test.tsx
- src/index.tsx
- src/internals.ts
- src/types/remoteFlows.ts
We want to provide consumers with a way to override the drawers for example with modals.
I added a demo but is commented to not break the premium benefits deployed app
> feat(zendesk-drawers) - replace zendesk drawers component

- example/src/CostCalculatorWithPremiumBenefits.tsx
- src/flows/CostCalculator/CostCalculatorFlow.tsx
- src/flows/CostCalculator/EstimationResults/EstimationResults.tsx
- src/flows/CostCalculator/index.ts
- src/index.tsx
We have some missing pieces of the edit functionality such as 
* not render the employer currency
* render an textfield to change the estimation title
I tried to the edit functionality to what we have now and we can do separated PRs addressing the missing functionality
In the [deployed review app](https://remote-flows-219159v49-remotecom.vercel.app/), you can check the functionality
> feat(cost-calculator) - do edit functionality but partially

- src/flows/CostCalculator/api.ts
- src/flows/Onboarding/api.ts
- src/flows/Onboarding/tests/OnboardingFlow.test.tsx
If countries aren't active, don't show it as they aren't ready to onboard
I detected twelve countries that we were showing like Barbados that we are not able to hire today
> feat(cost-calculator) - filter countries if they aren't avalaible

- .github/workflows/ci.yml
I notice that everything run together and we did have to wait 12min to know what happened with the unit tests.
This separates the unit tests to a separate job executed in parallel, that way we know if unit tests fail for some reason
Let me know what you think, the only thing i wanted is faster feedback for the unit tests to know what's happening
> fix(ci) - faster unit tests

- src/flows/Onboarding/components/OnboardingForm.tsx
We had a report from a partner that the Austria form it's having some issues.
Basically it's like the form fields from a previous step shows for a while and then they disappear.
I haven't been able to reproduce it but with this what I am trying to cause it's making react-hook-form to get destroyed and cleared up when we do navigations
> fix(onboarding) - add key to make form to clear when we navigate

- example/e2e/hiring-budget.spec.ts
- example/src/CostCalculatorWithPremiumBenefits.tsx
- src/flows/CostCalculator/CostCalculatorFlow.tsx
- src/flows/CostCalculator/CostCalculatorForm.tsx
- src/flows/CostCalculator/hooks.tsx
- src/flows/CostCalculator/jsonSchema.ts
- src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
- src/flows/CostCalculator/tests/utils.test.ts
- src/flows/CostCalculator/types.ts
- src/flows/CostCalculator/utils.ts
This PR adds an option to specify whether you want to use your budget or the employee's annual salary (default).
It also surfaces the error from the API in case an error is returned.
A couple of things:
- I have tried to use JSON schema to change the title of the field, but that didn't work, the same JSON schema works in the playground. To accommodate for that, I am setting it when the value is selected.
- I have added an onChange callback so that I can clear the error whenever any form field changes.
- I have surfaced the error in the UI if the request failed, I could not get the type right though unfortunately.
> feat: add hiring budget option

- .github/workflows/ci.yml
- .gitignore
- example/e2e/add-estimation.spec.ts
- example/e2e/annual-gross-salary.spec.ts
- example/e2e/edit-estimation.spec.ts
- example/e2e/helpers.ts
- example/e2e/hiring-budget.spec.ts
- example/playwright.config.ts
- example/src/CostCalculatorWithPremiumBenefits.tsx
We don't need to proxy calls on cost calculator as client token is enough
PS: client token not working well in all envs
In production company-currencies stopped working, while in the partners the currency conversion is not working
> fix(cost-calculator) - remove proxy
