src/components/form/fields/SelectField.tsx
src/components/form/fields/TextField.tsx
src/components/ui/form.tsx
src/components/ui/input.tsx
src/components/ui/select.tsx
src/flows/CostCalculator.tsx
src/lib/applyRules.ts
src/lib/applyTheme.ts
src/styles/global.css
src/theme.tsx
src/types.ts

Adds a customizable input. Support `rules` in ThemeProvider.
**How to test:**
Rende `<CostCalculator />` in the the consumer app.

feat(Input): Adds customizable input

---

package-lock.json
package.json
src/components/form/fields/RadioGroupField.tsx
src/components/form/fields/SelectField.tsx
src/components/form/fields/TextField.tsx
src/components/ui/radio-group.tsx
src/flows/CostCalculator.tsx

feat(RadioGroup): Adds radio group field

---

src/components/form/fields/FieldSetField.tsx
src/components/form/fields/SelectField.tsx
src/components/form/fields/types.ts
src/flows/CostCalculator.tsx

feat(fieldset): Add fieldset

---

src/components/form/fields/RadioGroupField.tsx
src/components/ui/radio-group.tsx
src/styles/global.css

Add radio color to be used by radio indicator so that by default color of the "circle" isn't white (primary color)

fix(radio): fix indicator color

---

src/components/form/fields/FieldSetField.tsx
src/components/form/fields/RadioGroupField.tsx
src/components/form/fields/SelectField.tsx
src/components/form/fields/TextField.tsx
src/flows/CostCalculator/CostCalculator.tsx
src/flows/CostCalculator/Results/CostCalculatorResults.tsx
src/flows/CostCalculator/Results/CostCalculatorResultsChart.tsx
tsup.config.ts

Adds and standardizes class names of flows and components. All class names should start with `RemoteFlows`

chore(class): Add class names 

---

src/RemoteFlowsProvider.tsx
src/index.tsx
src/types/remoteFlows.ts

Add theme props to the RemoteFlowsProvider

feat(theme-provider) - merge provider into remote flows

---

src/RemoteFlowsProvider.tsx
src/environments.ts
src/types/remoteFlows.ts
tsup.config.ts

I was having doubts if we should allow whatever string or just let people choose between staging / production.
i choose the latter

feat(baseUrl) - change the API baseUrl based on the environment

---

package.json

Update peerDependencies to:
```
"react": "^18 || ^19",
"react-dom": "^18 || ^19"
```

fix(peerDependencies): Update peerDependencies

---

README.md

Adds table of content to the README file

chore(README): Adds table of content

---

.changeset/seven-plants-juggle.md
README.md
src/components/form/fields/FieldSetField.tsx
src/components/form/fields/RadioGroupField.tsx
src/components/form/fields/SelectField.tsx
src/components/form/fields/TextField.tsx
src/components/ui/button.tsx

This PR adds field names to CSS classes to make targeting these fields with CSS easier.

feat(classname): Append field name to CSS classes

---

src/components/form/fields/FieldSetField.tsx
src/components/form/fields/TextField.tsx
src/flows/CostCalculator/CostCalculator.tsx
src/flows/CostCalculator/tests/CostCalculator.test.tsx
src/flows/CostCalculator/tests/fixtures.ts
src/flows/CostCalculator/tests/utils.test.ts
src/flows/CostCalculator/types.ts
src/flows/CostCalculator/utils.ts

This PR adds functionality to submit selected benefits through the Cost Calculator form when they are available.

feat(CostCalculator): Enable benefit submission when available

---

README.md
example/src/BasicCostCalculatorDefaultValues.tsx
src/flows/CostCalculator/CostCalculator.tsx
src/flows/CostCalculator/hooks.ts
src/flows/CostCalculator/tests/CostCalculator.test.tsx

Offer a button to reset the form fields of the CostCalculator.
Right now the button is hardcoded we can customize in the future if needed.
https://github.com/user-attachments/assets/bb75a650-3cef-4ada-95d1-fc68eb5448e9

feat(cost-calculator) - offer a way to reset the form fields

---

example/src/App.tsx
src/components/ui/badge.tsx
src/components/ui/button.tsx
src/flows/CostCalculator/CostCalculator.tsx
src/styles/global.css

I changed a bit the code to being able to change colors to the CostCalculator buttons

feat(cost-calculator) - themable buttons

---

src/components/form/fields/TextAreaField.tsx
src/components/form/fields/fieldsMapping.tsx
src/components/form/fields/types.ts
src/components/ui/textarea.tsx
src/flows/CostCalculator/fields.ts

Create textarea component, it's already done in a way that we can use it in the JSONSchemaForm
The count appears when we use the maxLength property

feat(textarea) - create textarea

---

example/src/App.tsx

I added two checkboxes to control if we want to show the benefits and cost breakdown in the Cost Calculator UI.
Currently, the PDF ignores the two fields which I think it's a bug in the API.

feat(cost-calculator) - adds checkboxes

---

.changeset/sixty-lemons-relate.md

Preparing release of the SDK to release premium benefits

feat(premium-benefits) - prepare release

---

src/components/form/fields/FileUploadField.tsx
src/components/form/fields/fieldsMapping.tsx
src/components/form/fields/types.ts
src/components/ui/file-uploader.tsx
src/flows/CostCalculator/fields.ts
src/flows/CostCalculator/types.ts

Create simple file upload, we can generate it from the fields file to render in the page.
The file can be multiple or not and we can remove the files that have been selected
https://github.com/user-attachments/assets/72be2c5e-988c-4e65-ab23-bd8af7526509

feat(file-upload) - create a simple file upload

---

.changeset/shiny-banks-sell.md

Release to npm the cost calculator flow && the placeholders

feat(cost-calculator) - new release cost calculator flow

---

src/flows/CostCalculator/hooks.ts
src/flows/CostCalculator/tests/hooks.test.tsx

We don't use the handleValidation internally as we rely in react-hook-form with the resolvers to run the validation onBlur and in the onSubmit
I added the validation and some tests to check that everything works smoothly

fix(cost-calculator) - fix the handleValidation

---

src/components/form/fields/CheckBoxField.tsx
src/components/form/fields/DatePickerField.tsx
src/components/form/fields/FileUploadField.tsx
src/components/form/fields/NumberField.tsx
src/components/form/fields/RadioGroupField.tsx
src/components/form/fields/SelectField.tsx
src/components/form/fields/TextAreaField.tsx
src/components/form/fields/TextField.tsx
src/components/form/fields/tests/CheckBoxField.test.tsx
src/components/form/fields/tests/DatePickerField.test.tsx
src/components/form/fields/tests/FileUploadField.test.tsx
src/components/form/fields/tests/RadioGroupField.test.tsx
src/components/form/fields/tests/TextAreaField.test.tsx
src/types/remoteFlows.ts

Follow up to https://github.com/remoteoss/remote-flows/pull/68 .
Adds support to custom components for remaining fields.

feat(custom components): Support of custom components for the remaining fields

---

example/src/App.css
example/src/ContractAmendment.tsx
src/flows/ContractAmendment/ContractAmendmentBack.tsx
src/flows/ContractAmendment/ContractAmendmentFlow.tsx
src/flows/ContractAmendment/ContractAmendmentForm.tsx
src/flows/ContractAmendment/context.ts
src/flows/ContractAmendment/hooks.ts
src/flows/ContractAmendment/tests/ContractAmendmentFlow.test.tsx
src/flows/ContractAmendment/utils.ts

Introduces the pre built `BackButton` component that enables users to navigate to the previous step in the contract amendment flow.

feat(Contract Amendment): Back button

---

example/src/Termination.tsx
src/flows/Termination/TerminationFlow.tsx
src/flows/Termination/TerminationForm.tsx
src/flows/Termination/context.ts
src/flows/Termination/hooks.ts

Render the user in the ack checkbox

feat(termination) - render the ack user

---

src/flows/ContractAmendment/hooks.test.tsx

Add tests for useContractAmendment hook

chore(contract amendments): add tests for useContractAmendment hook

---

src/components/form/fields/FileUploadField.tsx
src/components/form/fields/tests/FileUploadField.test.tsx
src/components/form/utils.ts
src/flows/Termination/TerminationFlow.tsx

I did some changes to the FileUploadField to transform the files uploaded into base64.
Right now, the termination endpoint is failing with a 500 error but I think it's a problem in the BE endpoint.
The payload is in good shape as it doesn't send a 422

feat(files) - transform files to base64 to be in the desired endpoint format

---

example/src/ContractAmendment.tsx
src/flows/ContractAmendment/ContractAmendmentForm.tsx
src/flows/ContractAmendment/hooks.ts
src/flows/ContractAmendment/utils.ts
src/flows/useStepState.test.tsx
src/flows/useStepState.ts

Introduces `useStepState` hook for managing multi-step form state, handling step navigation and form value accumulation across steps.

feat(flows): useStepState hook

---

src/tests/useAuth.test.tsx
src/useAuth.ts
tsup.config.ts

Adds client name and version to the HTTP headers.

chore(observability): Add versioning headers

---

src/components/form/fields/EmailField.tsx
src/components/form/fields/fieldsMapping.tsx
src/components/form/fields/types.ts
src/flows/Termination/jsonSchema.ts

Create the email field, this way we support email types declared in the json schema.

feat(termination) - create email field

---

.changeset/lazy-baboons-add.md

- Support proxying request
- Contract Amendments (WIP)
- Offboarding (WIP)

feat(proxy) - add changeset

---

src/flows/ContractAmendment/hooks.test.tsx
src/flows/ContractAmendment/hooks.ts

When conditional fields are changed they should be visible when navigation back to the form.
https://www.loom.com/share/c3813d17c52b4e4580a6d6d2a9bc2868

fix(contract amendment): refactor field values handling for form navigation

---

example/src/App.css
example/src/Dialog.tsx
example/src/Termination.tsx
example/src/TerminationDialog.tsx
example/src/utils.ts

Add an advanced example of the termination

docs(termination) - add a more advance example of the termination

---

example/src/Termination.tsx
src/components/form/fields/CheckBoxField.tsx
src/components/form/fields/DatePickerField.tsx
src/components/form/fields/FileUploadField.tsx
src/components/form/fields/RadioGroupField.tsx
src/components/form/fields/SelectField.tsx
src/components/form/fields/TextAreaField.tsx
src/components/form/fields/TextField.tsx
src/components/ui/form.tsx
src/flows/Termination/README.md
src/flows/Termination/TimeOff.tsx
src/flows/Termination/tests/TimeOff.test.tsx

docs(timeoff) -  improve docs

---

.changeset/orange-hounds-cut.md
src/flows/Termination/TerminationForm.tsx
src/flows/Termination/hooks.ts
src/flows/Termination/tests/TerminationFlow.test.tsx

1 bug was going to the second step, filling the form, selecting will_challenge_termination to true and the conditional description field was not showing
2 bug is select a radio immediately that allows a conditional field to appear, it didn't happen
In the video, you can take a look at both bugs 
https://github.com/user-attachments/assets/1d8f72f6-2394-4a12-940c-1cd145b51fb2

fix(termination) - fix 2 bugs related to radios

---

src/flows/Termination/hooks.ts

I prepared a loom showcasing what was not working on main.
Basically we were setting the values okay once but not always

fix(termination) - fix steps as it gave false positives

---

src/components/form/fields/FileUploadField.tsx
src/components/ui/file-uploader.tsx

Fix onChange emission, I also noticed that the previous changes to the fileUploader didn't get to the main branch :(

fix(file-uploaders) - fix onChange emission

---

src/components/form/fields/DatePickerField.tsx
src/flows/ContractAmendment/tests/ContractAmendmentFlow.test.tsx
src/flows/Termination/tests/TerminationFlow.test.tsx
src/tests/testHelpers.ts

Change datepicker utils to be able to select multiple datepickers in a form

fix datepicker test utils

---

src/lib/utils.ts

Remove unused and duplicated `convertToCents` code

chore(convertToCents): remove unused code

---

src/components/form/fields/MoneyField.tsx
src/components/form/fields/fieldsMapping.tsx
src/components/form/fields/tests/MoneyField.test.tsx

Adds MoneyField component with support for a custom component

feat(money field): Add MoneyField component

---

src/flows/ContractAmendment/README.md

Adds README for contract amendments detailing the setup, usage examples, and API components.

chore(Contract Amendment): Add README

---

src/flows/Onboarding/OnboardingSubmit.tsx

Adds support to the submit button

feat(Onboarding Flow): Add submit button

---

example/src/Onboarding.tsx
src/flows/Onboarding/BasicInformationStep.tsx
src/flows/Onboarding/BenefitsStep.tsx
src/flows/Onboarding/ContractDetailsStep.tsx
src/flows/Onboarding/OnboardingFlow.tsx
src/flows/Onboarding/hooks.ts

I generated the component, fetch the json schema and submit it, we probably have some bugs related to the submission as I only have tested that the happy path worked

feat(contract-details) - submit the contract details

---

src/flows/ContractAmendment/hooks.ts
src/flows/Onboarding/hooks.ts

Restore field values for current step when navigating back in the Onboarding flows (applied the same strategy to ContractAmendment as well)

fix(onboarding): fix initial values when navigating back

---

src/components/form/utils.ts
src/flows/Onboarding/BenefitsStep.tsx

This allows us to preselect the fields based on the json-schema.
We should do something more clever to integrate this in all forms

fix benefits initial selection

---

src/components/form/JSONSchemaForm.tsx
src/components/form/fields/FieldSetField.tsx

Fix `FieldSetField` to accept a components prop for custom component rendering.

fix(custom component): fix component prop on fieldsets

---

example/src/App.css
example/src/Onboarding.tsx
example/src/OnboardingWithCustomBenefits.tsx

- Added error message display for API errors in the onboarding process.  
- Introduced new button styles for submit and reset actions.

chore(example): UI improvements to the onboarding example

---

src/components/form/yupValidationResolver.ts
src/flows/Onboarding/tests/OnboardingFlow.test.tsx
src/flows/Onboarding/tests/fixtures.ts

I'm dividing the onboarding flow tests in different PRs to avoid having a gigantic diff

docs(onboarding-flow) - add tests

---

example/src/Onboarding.tsx

add steps to example

---

src/flows/Onboarding/hooks.ts
src/flows/Termination/hooks.ts

Used the same style that we use in ContractAmendments, it was suggested in a previous PR

fix(jsfModify) - change how we apply it

---

example/src/OnboardingWithCustomBenefits.tsx
src/components/form/utils.ts
src/flows/ContractAmendment/tests/ContractAmendmentFlow.test.tsx
src/flows/Onboarding/hooks.ts
src/flows/Termination/tests/TerminationFlow.test.tsx

Removes the logic that converts empty strings to null in payloads submitted to the API.

fix(utils): Remove logic that converts empty strings to null

---

src/index.tsx

feat(types) - add missed types

---

src/flows/ContractAmendment/ContractAmendmentConfirmationForm.tsx
src/flows/ContractAmendment/ContractAmendmentForm.tsx
src/flows/CostCalculator/CostCalculatorForm.tsx
src/flows/Onboarding/BasicInformationStep.tsx
src/flows/Onboarding/BenefitsStep.tsx
src/flows/Onboarding/ContractDetailsStep.tsx
src/flows/Onboarding/OnboardingInvite.tsx
src/flows/Termination/AdditionalDetailsForm.tsx

Modify onSuccess callbacks to support promises

docs(flows)- Modify on success callbacks

---

src/components/form/fields/ForcedValueField.tsx

Updated ForcedValueField component to conditionally render title and description based on the presence of the statement. If the statement is undefined, it now falls back to description.

fix(ForcedValueField) - handle undefined statement gracefully

---

src/components/form/fields/HiddenField.tsx
src/components/form/fields/fieldsMapping.tsx
src/components/form/fields/types.ts

- Introduced a new HiddenField component for use in forms.
- Updated fieldsMap to include the new 'hidden' type.

feat(fields) - add HiddenField component and update fields mapping

---

example/src/Onboarding.tsx
src/flows/ContractAmendment/hooks.ts
src/flows/ContractAmendment/utils.ts
src/flows/Onboarding/OnboardingForm.tsx
src/flows/Onboarding/hooks.ts
src/flows/Onboarding/tests/utils.test.ts
src/flows/Onboarding/utils.ts
src/flows/Termination/utils.ts
src/flows/useStepState.ts

This PR adds a `metadata` property to the onboarding hook. In this field, we're including prettified form values and field label, so it can be used in the review step.

feat(onboarding): Prettify form values

---

src/components/form/fields/FieldSetField.tsx

Fixes a bug where we weren't displaying JSON schema statements on fieldsets.

fix(fieldset): render statements for fieldsets

---

.changeset/all-hoops-scream.md

We're adding a new changeset to release some fixes

new release

---

src/flows/Onboarding/hooks.ts
src/flows/Onboarding/tests/OnboardingFlow.test.tsx
src/flows/Onboarding/tests/OnboardingInvite.test.tsx
src/flows/Onboarding/tests/fixtures.ts

Add tests for the onboarding invite component

feat(onboarding-invite) - add tests for the onboarding invite

---

src/components/form/fields/tests/WorkScheduleField.test.tsx

Adds unit tests to WorkScheduleField field component.

chore(WorkScheduleField): write unit tests

---

README.md

Added detailed instructions for running the SDK locally

docs(README): add development setup instructions

---

src/components/form/fields/tests/CheckBoxField.test.tsx
src/components/form/fields/tests/CountryField.test.tsx
src/components/form/fields/tests/DatePickerField.test.tsx
src/components/form/fields/tests/FileUploadField.test.tsx
src/components/form/fields/tests/NumberField.test.tsx
src/components/form/fields/tests/RadioGroupField.test.tsx
src/components/form/fields/tests/SelectField.test.tsx
src/components/form/fields/tests/TextAreaField.test.tsx
src/components/form/fields/tests/TextField.test.tsx
src/components/form/fields/tests/WorkScheduleField.test.tsx
src/flows/ContractAmendment/tests/ContractAmendmentFlow.test.tsx
src/flows/CostCalculator/CostCalculatorFlow.tsx
src/flows/CostCalculator/CostCalculatorForm.tsx
src/flows/CostCalculator/README.md
src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx
src/flows/CostCalculator/tests/hooks.test.tsx

The only I found to solve this was setting shouldUnregister: false, without that the form didn't reset on the onSuccess handler
But shouldUnregister has some gotchas, the region field will stay in the values, that's why I am cleaning the values.

feat(cost-calculator) - add testing

---

example/src/Onboarding.tsx
example/src/OnboardingAlertStatuses.tsx
example/src/OnboardingWithCustomBenefits.tsx
example/src/OnboardingWithoutSelectCountryStep.tsx
example/src/ReviewStep.tsx
src/flows/Onboarding/hooks.ts
src/flows/Onboarding/types.ts

Fix bug when you did the onboarding completing all the steps and the invite didn't work
Unify example code ReviewStep in a component to avoid copy & pasting

fix(onboarding) - fix invitation process

---

.changeset/better-women-end.md

I will do a release this afternoon with the latest changes

add changeset for alpha 7

---

src/flows/Onboarding/index.ts

I missed exporting the CreditRiskStatus type

fix(credit-score) - miss export

---

src/flows/Onboarding/hooks.ts
src/flows/Onboarding/tests/OnboardingFlow.test.tsx

As we talked yesterday the company status can change until you get to the last step.
We refetch the company data every time we submit

feat(onboarding) - refetch company after submitting each step

---

example/src/OnboardingAlertStatuses.tsx
example/src/ReviewStep.tsx
src/flows/Onboarding/OnboardingInvite.tsx
src/flows/Onboarding/api.ts
src/flows/Onboarding/hooks.ts
src/flows/Onboarding/index.ts
src/flows/Onboarding/types.ts

Add referred status to the demo
We export employment and refetchEmployment which will be used later

feat(onboarding) - add referred status

---

src/flows/Onboarding/hooks.ts
src/flows/Onboarding/tests/OnboardingFlow.test.tsx
src/flows/Onboarding/tests/OnboardingInvite.test.tsx
src/flows/useStepState.test.tsx
src/flows/useStepState.ts
src/tests/testHelpers.ts

When the status in a finalized step, let's jump to the review step automatically

feat(onboarding)  - jump to the review step

---

example/src/App.css
example/src/BasicCostCalculator.tsx
example/src/Components.tsx
example/src/ContractAmendment.tsx
example/src/Onboarding.tsx
example/src/Termination.tsx
src/flows/ContractAmendment/ContractAmendmentBack.tsx
src/flows/ContractAmendment/ContractAmendmentSubmit.tsx
src/flows/ContractAmendment/tests/ContractAmendmentBack.test.tsx
src/flows/ContractAmendment/tests/ContractAmendmentSubmit.test.tsx
src/flows/CostCalculator/CostCalculatorResetButton.tsx
src/flows/CostCalculator/CostCalculatorSubmitButton.tsx
src/flows/CostCalculator/tests/CostCalculatorResetButton.test.tsx
src/flows/CostCalculator/tests/CostCalculatorSubmitButton.test.tsx
src/flows/Onboarding/OnboardingBack.tsx
src/flows/Onboarding/OnboardingInvite.tsx
src/flows/Onboarding/OnboardingSubmit.tsx
src/flows/Onboarding/tests/OnboardingBack.test.tsx
src/flows/Onboarding/tests/OnboardingInvite.test.tsx
src/flows/Onboarding/tests/OnboardingSubmit.test.tsx
src/flows/Termination/TerminationBack.tsx
src/flows/Termination/TerminationSubmit.tsx
src/flows/Termination/tests/TerminationBack.test.tsx
src/flows/Termination/tests/TerminationSubmit.test.tsx
src/types/remoteFlows.ts

We allow now replacing the buttons with your own ones.
Looks like a big PR but that's due to the tests, I found bugs with some buttons of the flows, thanks to the extensive testing
I added comments where I found them

feat(components) - replace buttons with your own

---

src/flows/Onboarding/api.ts
src/flows/Onboarding/hooks.ts
src/flows/Onboarding/tests/OnboardingFlow.test.tsx

Found a bug in the review, when you have an employment with the status invited
The contract details weren't loading correctly, add some assertions to the test to make sure we don't have this regression in the future

fix(onboarding) - skip review and check that the contract details are correctly displayed

---

src/flows/Onboarding/hooks.ts
src/flows/Onboarding/tests/OnboardingFlow.test.tsx

Fix the flickering state while we skip to the review step
https://github.com/user-attachments/assets/1188a814-a250-4704-92f7-ce2c0b1b1f53

fix(onboarding) - fix flickering state when skipping to review

---

src/flows/CostCalculator/CostCalculatorFlow.tsx
src/flows/CostCalculator/hooks.ts
src/flows/CostCalculator/types.ts
src/flows/Termination/TerminationFlow.tsx
src/flows/Termination/hooks.ts
src/flows/types.ts

Move the JSModify types to a shared folder instead of using the CostCalculator folder

fix types folder

---

example/src/OnboardingWithoutSelectCountryStep.tsx
src/flows/Onboarding/api.ts
src/flows/Onboarding/hooks.tsx
src/flows/Onboarding/tests/OnboardingFlow.test.tsx
src/flows/Onboarding/types.ts

I have refactored the jsfModify to allow to differenciate between each step

refactor jsmodify for the onboarding

---

src/flows/ContractAmendment/README.md
src/flows/Onboarding/README.md
src/flows/Onboarding/hooks.tsx
src/flows/Termination/README.md

Add docs for the onboarding flow, improve some readmes in the termination / contract amendments around the table of contents
Removed owner_id because I detected that we weren't using it

docs(onboarding)- add docs

---

README.md

fix(readme) - fix gateway typo

---

.changeset/wild-shrimps-remain.md

prepare release for alpha 14

---

README.md
example/package-lock.json
example/package.json

For some reason when trying to run the app in local,
I suffered this error
```
code: 'MODULE_NOT_FOUND',
requireStack: [
'/Users/gabriel/remote/remote-flows/example/node_modules/@swc/core/binding.js',
'/Users/gabriel/remote/remote-flows/example/node_modules/@swc/core/index.js',
'/Users/gabriel/remote/remote-flows/example/node_modules/@vitejs/plugin-react-swc/index.cjs',
'/Users/gabriel/remote/remote-flows/example/vite.config.ts',
'/Users/gabriel/remote/remote-flows/example/node_modules/vite/dist/node/chunks/dep-glQox-ep.js'
```
I solved it removing lock, installing and it seems now the dependencies are in the lock
No idea what happened here
Added instructions on how to run the project with npm link

fix example lock

---

src/flows/Onboarding/tests/utils.test.ts
src/flows/Onboarding/utils.ts

Didn't make sense to add desiredCurrency in the field, what we need to extract is the currency of the field not the desiredCurrency of the company

fix(onboarding) - fix currency value instead of desiredCurrency

---

example/api/get_token.js
example/src/App.tsx

Only show the cost calculator demos on our vercel deployed app
Disabled the getToken endpoint in production in case someone uses Curl to exchange a token

feat(cost-calculator) - only show cost calculator in production

---

example/src/OnboardingWithoutSelectCountryStep.tsx
src/flows/Onboarding/OnboardingForm.tsx
src/flows/Onboarding/SaveDraftButton.tsx
src/flows/Onboarding/hooks.tsx
src/flows/Onboarding/tests/SaveDraftButton.test.tsx

I didn't notice before but if you sent a invalid form state the draft button should validate if the form is correct or not.
So now we first trigger the form validation if it's correct we continue
We have implemented a fix generating creating a custom event and handling the logic in the OnboardingForm

fix(onboarding) - Trigger form validation when using the draft button

---

example/package-lock.json
example/package.json

For some reason, vercel was not picking up the latest changes so I decided to pin the version of the last package.

pin the package version

---

example/api/get_token.js
example/dev_server.js
example/src/CostCalculatorWithPremiumBenefits.tsx

This commit adds the ability to pass options to the cost calculator exports, so that they can benefit of the premium benefits/breakdowns features.

feat: use options for pdf export

---

example/src/App.tsx
example/src/CostCalculatorWithPremiumBenefits.tsx

Hide the rest of the cost calculator in production.
Changed some labels on the premium benefits that we're showing

hide demos on production

---

example/src/App.tsx
example/src/Components.tsx
example/src/CostCalculatorWithPremiumBenefits.tsx
example/src/css/main.css
src/components/form/fields/TextField.tsx
src/components/form/fields/tests/TextField.test.tsx
src/flows/CostCalculator/hooks.tsx
src/types/remoteFlows.ts

Style premium benefits adding the currency and style a bit the rest of the components used here.
I went with custom components as it looks like the fastest way to style the currency
Besides that, did a change to the types as there were some types missing

feat(cost-calculator) - style premium benefits

---

example/src/Components.tsx
example/src/OnboardingWithoutSelectCountryStep.tsx
example/src/css/main.css

Add more custom inputs as I was debugging the onboarding for some bugfixes

feat(onboarding) - add more custom inputs

---

src/flows/CostCalculator/CostCalculatorForm.tsx

Remove suspicious code that could be one breaking the onboarding

remove suspicious code

---

src/components/form/fields/FieldSetField.tsx

Move they key to the fragment to see if we this we solve the bug that the partner is having

fix fieldset field key order

---

example/src/CostCalculatorWithPremiumBenefits.tsx
src/flows/CostCalculator/EstimationResults/EstimationResults.tsx

Add the ability to remove an estimate

feat(cost-calculator) - add onDelete handler

---

src/flows/CostCalculator/hooks.tsx

Reverts remoteoss/remote-flows#406

Revert "feat(cost-calculator) - change currency order"

---

src/components/shared/zendesk-drawer/api.ts
src/flows/CostCalculator/api.ts
src/flows/Onboarding/api.ts
src/flows/Termination/hooks.ts

Clean unnecessary headers, we still need it for some functions that make headers required, probably you need fix the openAPI spec because it doesn't make sense that some endpoints need it and others don't

feat(headers) - clean unnecessary headers

---

src/flows/CostCalculator/README.md
src/flows/CostCalculator/SummaryResults/SummaryResults.tsx
src/flows/CostCalculator/tests/SummaryResults.test.tsx

Fix the summary results as we weren't grouping by country the estimations.
Add docs && add tests for this one

docs(summary) - improve summary results logic && docs

---

example/src/CostCalculatorWithPremiumBenefits.tsx
src/client/types.gen.ts
src/flows/CostCalculator/EstimationResults/EstimationResults.tsx
src/flows/CostCalculator/README.md
src/flows/CostCalculator/hooks.tsx
src/flows/CostCalculator/tests/utils.test.ts
src/flows/CostCalculator/types.ts
src/flows/CostCalculator/utils.ts

Add management fee to the results component.

Add management fee to the results

---

example/e2e/annual-gross-salary.spec.ts
src/flows/CostCalculator/EstimationResults/EstimationResults.tsx
src/styles/global.css

This commit adds the annual gross salary in the header, using the employee currency.

feat: show annual gross salary in header

---

src/flows/CostCalculator/EstimationResults/EstimationResults.tsx

We were not retrieving the correct value for the nested items for the regionalAmount, we were getting the employer amount and we didn't notice.
We need to build tests for this component to make sure that everything works as we like

Fix children regional amount

---

src/flows/CostCalculator/EstimationResults/EstimationResults.tsx

I notice that the GB flag wasn't working, flagpack in this case has several examples for Wales, Britain, Ireland etc...
I decide to go with a map to fix this quick

fix(estimate-results) - fix flag

---

src/flows/CostCalculator/EstimationResults/EstimationResults.tsx

Fix copy to clarify Remote's Term of service and fix typo enrollment

feat(estimations) - fix copy

---

example/src/CostCalculatorWithPremiumBenefits.tsx
src/flows/CostCalculator/hooks.tsx

Fix jsfModify for the hiring budget

fix(cost-calculator) - fix hiring jsfModify

---

example/src/CostCalculatorWithPremiumBenefits.tsx
src/flows/CostCalculator/CostCalculatorFlow.tsx
src/flows/CostCalculator/tests/CostCalculatorFlow.test.tsx

When we edit the management fee, we pass the management fee value and we override the value set in the form

fix(cost-calculator) - override management fee when edit

---

example/api/get_token.js
example/src/OffboardingRequestModal.tsx
example/src/Termination.tsx
src/flows/Termination/TerminationDialogInfoContent/TerminationDialogInfoContent.tsx
src/flows/Termination/index.ts

Offer to our partners a way to have content about the termination process, we put some classes in there to allow users to give different styles.
I went for the safest route, if they ask for more customizations like having power about what it's render, we can always do it later.

feat(termination) - add termination dialog info content
